#ifndef	__ROMS_325_rom_H__
#define	__ROMS_325_rom_H__
PRCIDType	small_PRC_ROMS_325_rom[]	= { 
                           {          sysFileTBoot,        sysFileCSystem, 0 },
                           { 0, 0, 0 }
};
PRCIDType	large_PRC_ROMS_325_rom[]	= { 
                           {         sysFileTPanel, sysFileCWirelessPanel, 0 },
                           {         sysFileTPanel,     sysFileCShortCuts, 0 },
                           {         sysFileTPanel,         sysFileCOwner, 0 },
                           {         sysFileTPanel,  sysFileCNetworkPanel, 0 },
                           {         sysFileTPanel,       sysFileCGeneral, 0 },
                           {         sysFileTPanel,       sysFileCFormats, 0 },
                           {         sysFileTPanel,     sysFileCDigitizer, 0 },
                           {         sysFileTPanel,    sysFileCModemPanel, 0 },
                           {         sysFileTPanel,       sysFileCButtons, 0 },
                           {          sysFileTsdio,          sysFileCnett, 0 },
                           {          sysFileTsdio,          sysFileCping, 0 },
                           {   sysFileTApplication,     sysFileCMessaging, 0 },
                           {   sysFileTApplication,          sysFileCToDo, 0 },
                           {   sysFileTApplication,          sysFileCSync, 0 },
                           {   sysFileTApplication,         sysFileCSetup, 0 },
                           {   sysFileTApplication,      sysFileCSecurity, 0 },
                           {   sysFileTApplication,        sysFileCRFDiag, 0 },
                           {   sysFileTApplication,   sysFileCPreferences, 0 },
                           {   sysFileTApplication,          sysFileCMemo, 0 },
                           {   sysFileTApplication,          sysFileCMail, 0 },
                           {   sysFileTApplication, sysFileCMACUtilSerial, 0 },
                           {   sysFileTApplication,      sysFileCLauncher, 0 },
                           {   sysFileTApplication,       sysFileCExpense, 0 },
                           {   sysFileTApplication,      sysFileCDatebook, 0 },
                           {   sysFileTApplication,       sysFileCClipper, 0 },
                           {   sysFileTApplication,    sysFileCCalculator, 0 },
                           {   sysFileTApplication,       sysFileCAddress, 0 },
                           {   sysFileTApplication,      sysFileCActivate, 0 },
                           {     sysFileTExtension,          sysFileCpalm, 0 },
                           {       sysFileTLibrary,        sysFileCWebLib, 0 },
                           {       sysFileTLibrary,        sysFileCSecLib, 0 },
                           {       sysFileTHtalLib,       sysFileCTCPHtal, 0 },
                           {       sysFileTHtalLib,       sysFileCPADHtal, 0 },
                           {          sysFileTneti,           sysFileCram, 0 },
                           {          sysFileTneti,          sysFileCloop, 0 },
                           {          sysFileTneti,          sysFileCslip, 0 },
                           {          sysFileTneti,           sysFileCppp, 0 },
                           {       sysFileTLibrary,           sysFileCNet, 0 },
                           {       sysFileTLibrary,          sysFileCrdio, 0 },
                           {        sysFileTExgLib,         sysFileCIrLib, 0 },
                           {       sysFileTLibrary,       sysFileCINetLib, 0 },
                           {    sysFileTUIAppShell,        sysFileCSystem, 0 },
                           {        sysFileTKernel,        sysFileCSystem, 0 },
                           {        sysFileTSystem,        sysFileCSystem, 0 },
                           { 0, 0, 0 }
};
#endif	/* __ROMS_325_rom_H__ */
