#ifndef	__ROMS_350_rom_H__
#define	__ROMS_350_rom_H__
PRCIDType	small_PRC_ROMS_350_rom[]	= { 
                           {          sysFileTBoot,        sysFileCSystem, 0 },
                           {      sysFileTSmallHal,        sysFileCSystem, 0 },
                           { 0, 0, 0 }
};
PRCIDType	large_PRC_ROMS_350_rom[]	= { 
                           {        sysFileTSystem,        sysFileCSystem, 0 },
                           {        sysFileTBigHal,        sysFileCSystem, 0 },
                           {        sysFileTSplash,        sysFileCSystem, 0 },
                           {        sysFileTSystem,        sysFileCSystem, 1 },
                           {        sysFileTSplash,        sysFileCSystem, 1 },
                           {    sysFileTUartPlugIn,     sysFileCUart328EZ, 0 },
                           {    sysFileTUartPlugIn,     sysFileCUart328EZ, 1 },
                           {       sysFileTDefault,    sysFileCModemPanel, 0 },
                           {       sysFileTDefault,    sysFileCModemPanel, 0 },
                           {        sysFileTKernel,        sysFileCSystem, 0 },
                           {       sysFileTLibrary, sysFileCSerialWrapper, 0 },
                           {    sysFileTUIAppShell,        sysFileCSystem, 0 },
                           {   sysFileTApplication,      sysFileCLauncher, 0 },
                           {   sysFileTApplication,      sysFileCLauncher, 1 },
                           {   sysFileTApplication,   sysFileCPreferences, 0 },
                           {   sysFileTApplication,   sysFileCPreferences, 1 },
                           {   sysFileTApplication,      sysFileCSecurity, 0 },
                           {   sysFileTApplication,      sysFileCSecurity, 1 },
                           {   sysFileTApplication,       sysFileCAddress, 0 },
                           {   sysFileTApplication,       sysFileCAddress, 1 },
                           {   sysFileTApplication,      sysFileCDatebook, 0 },
                           {   sysFileTApplication,      sysFileCDatebook, 1 },
                           {   sysFileTApplication,          sysFileCMemo, 0 },
                           {   sysFileTApplication,          sysFileCMemo, 1 },
                           {   sysFileTApplication,          sysFileCToDo, 0 },
                           {   sysFileTApplication,          sysFileCToDo, 1 },
                           {   sysFileTApplication,    sysFileCCalculator, 0 },
                           {   sysFileTApplication,    sysFileCCalculator, 1 },
                           {   sysFileTApplication,       sysFileCExpense, 0 },
                           {   sysFileTApplication,       sysFileCExpense, 1 },
                           {   sysFileTApplication,          sysFileCMail, 0 },
                           {   sysFileTApplication,          sysFileCMail, 1 },
                           {         sysFileTPanel,     sysFileCDigitizer, 0 },
                           {         sysFileTPanel,     sysFileCDigitizer, 1 },
                           {         sysFileTPanel,       sysFileCGeneral, 0 },
                           {         sysFileTPanel,       sysFileCGeneral, 1 },
                           {         sysFileTPanel,       sysFileCButtons, 0 },
                           {         sysFileTPanel,       sysFileCButtons, 1 },
                           {         sysFileTPanel,    sysFileCModemPanel, 0 },
                           {         sysFileTPanel,    sysFileCModemPanel, 1 },
                           {         sysFileTPanel,       sysFileCFormats, 0 },
                           {         sysFileTPanel,       sysFileCFormats, 1 },
                           {         sysFileTPanel,         sysFileCOwner, 0 },
                           {         sysFileTPanel,         sysFileCOwner, 1 },
                           {         sysFileTPanel,     sysFileCShortCuts, 0 },
                           {         sysFileTPanel,     sysFileCShortCuts, 1 },
                           {   sysFileTApplication,          sysFileCSync, 0 },
                           {   sysFileTApplication,          sysFileCSync, 1 },
                           {       sysFileTHtalLib,       sysFileCPADHtal, 0 },
                           {        sysFileTExgLib,         sysFileCIrLib, 0 },
                           {    sysFileTVirtPlugin,    sysFileCVirtIrComm, 0 },
                           {    sysFileTVirtPlugin,    sysFileCVirtIrComm, 1 },
                           {       sysFileTLibrary,           sysFileCNet, 0 },
                           {          sysFileTneti,           sysFileCppp, 0 },
                           {          sysFileTneti,           sysFileCppp, 1 },
                           {          sysFileTneti,          sysFileCslip, 0 },
                           {          sysFileTneti,          sysFileCslip, 1 },
                           {          sysFileTneti,          sysFileCloop, 0 },
                           {         sysFileTPanel,  sysFileCNetworkPanel, 0 },
                           {         sysFileTPanel,  sysFileCNetworkPanel, 1 },
                           {          sysFileTsdio,          sysFileCping, 0 },
                           {          sysFileTsdio,          sysFileCnett, 0 },
                           {       sysFileTHtalLib,       sysFileCTCPHtal, 0 },
                           {   sysFileTApplication,         sysFileCSetup, 0 },
                           {   sysFileTApplication,         sysFileCSetup, 1 },
                           { 0, 0, 0 }
};
#endif	/* __ROMS_350_rom_H__ */
